import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.166.1/build/three.module.js';
const canvas=document.querySelector('#game'), renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x05090d);scene.fog=new THREE.FogExp2(0x071018,.028);const camera=new THREE.PerspectiveCamera(54,1,.1,100);const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0x55d9ff,0x0c090b,1.7));const moon=new THREE.DirectionalLight(0x93dfff,2.7);moon.position.set(-7,12,4);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);scene.add(moon);
const floor=new THREE.Mesh(new THREE.CylinderGeometry(15,15,.55,56),new THREE.MeshStandardMaterial({color:0x121a1e,roughness:.88,metalness:.25}));floor.receiveShadow=true;floor.position.y=-.3;scene.add(floor);const grid=new THREE.GridHelper(30,30,0x1b7b87,0x182a31);grid.position.y=.01;scene.add(grid);
const gate=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(4.1,.17,10,48),new THREE.MeshStandardMaterial({color:0x00e5ff,emissive:0x00b5cc,emissiveIntensity:3}));ring.rotation.x=Math.PI/2;ring.position.y=.2;gate.add(ring);scene.add(gate);for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=Math.random()*12+2;const pillar=new THREE.Mesh(new THREE.BoxGeometry(.5,Math.random()*2+1.5,.5),new THREE.MeshStandardMaterial({color:0x202a2e,roughness:1}));pillar.position.set(Math.cos(a)*r,.5,Math.sin(a)*r);pillar.castShadow=true;scene.add(pillar)}
const cast=(o,s)=>{o.traverse(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true}});o.scale.setScalar(s);return o};
function fighter(name,color,weapon){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color,roughness:.52,metalness:.4}),dark=new THREE.MeshStandardMaterial({color:0x161c23,roughness:.7});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.8,5,10),mat);body.position.y=1.05;const head=new THREE.Mesh(new THREE.SphereGeometry(.29,14,12),new THREE.MeshStandardMaterial({color:0xd5a17d,roughness:.8}));head.position.y=1.75;const shoulder=new THREE.Mesh(new THREE.BoxGeometry(.9,.16,.42),dark);shoulder.position.y=1.38;const blade=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,1.2),new THREE.MeshStandardMaterial({color:weapon,metalness:.8,roughness:.2,emissive:weapon,emissiveIntensity:.22}));blade.position.set(.48,1.05,.3);blade.rotation.x=Math.PI/2;g.add(body,head,shoulder,blade);g.userData={name,body,blade,health:100,max:100,attackCd:0,hit:0,velocity:new THREE.Vector3(),alive:true};return cast(g,1)}
const roster=[{name:'KAEL',role:'VOIDBORN WARRIOR',color:0x182934,weapon:0x00e5ff,initial:'K',desc:'Balanced katana fighter. Reliable defense and Void energy.',hp:120,speed:6,power:17},{name:'ARIA',role:'PHANTOM BLADE',color:0x4b216d,weapon:0xae67ff,initial:'A',desc:'Agile dual-blade specialist. Fast attacks and evasive movement.',hp:90,speed:7.5,power:13},{name:'BRAM',role:'IRON MONK',color:0x603525,weapon:0xffc857,initial:'B',desc:'Heavy staff guardian. Greater health and devastating strikes.',hp:155,speed:4.7,power:24}];
let selected=null,hero=null,enemies=[],game=false,wave=1,xp=0,coins=0,stamina=100,voidEnergy=45,locked=null,renderScale=Math.min(devicePixelRatio,1.5),frameSamples=[],lastPerformanceCheck=0;const keys={},ui={health:document.querySelector('#health'),stamina:document.querySelector('#stamina'),void:document.querySelector('#void'),enemy:document.querySelector('#enemyHealth'),target:document.querySelector('#targetName'),heroName:document.querySelector('#heroName'),heroClass:document.querySelector('#heroClass'),portrait:document.querySelector('#portrait'),wave:document.querySelector('#wave'),xp:document.querySelector('#xp'),coins:document.querySelector('#coins'),notice:document.querySelector('#notice'),enemyHud:document.querySelector('#enemyHud')};
const audio={context:null,enabled:false,enable(){if(!this.context)this.context=new AudioContext();this.context.resume();this.enabled=true},play(frequency,duration=.06,type='sine',volume=.035){if(!this.enabled)return;const osc=this.context.createOscillator(),gain=this.context.createGain();osc.type=type;osc.frequency.value=frequency;gain.gain.setValueAtTime(volume,this.context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,this.context.currentTime+duration);osc.connect(gain).connect(this.context.destination);osc.start();osc.stop(this.context.currentTime+duration)}};
const characterEl=document.querySelector('#characters');roster.forEach((c,i)=>{const e=document.createElement('button');e.className='character';e.innerHTML=`<div class="avatar" style="--tone:#${c.color.toString(16)}" data-initial="${c.initial}"></div><h2>${c.name}</h2><small>${c.role}</small><p>${c.desc}</p>`;e.onclick=()=>{selected=i;document.querySelectorAll('.character').forEach(x=>x.classList.remove('active'));e.classList.add('active');document.querySelector('#launch').disabled=false};characterEl.append(e)});
function notify(text){ui.notice.textContent=text;ui.notice.style.opacity=1;clearTimeout(notify.t);notify.t=setTimeout(()=>ui.notice.style.opacity=0,1300)}
function spawnEnemy(i){const hue=[0x75222d,0x562165,0x7c3d24][i%3],e=fighter(['RUSHER','VOID MAGE','GUARDIAN'][i%3],hue,0xff3040);const a=Math.random()*Math.PI*2;e.position.set(Math.cos(a)*10,0,Math.sin(a)*10);e.userData.max=e.userData.health=55+wave*18+(i%3)*13;e.userData.speed=2.1+(i%3)*.35;e.userData.power=6+wave*2;e.userData.phase=Math.random()*6;scene.add(e);enemies.push(e)}
function start(){audio.enable();document.querySelector('#pause').textContent='Ⅱ';document.querySelector('#pause').setAttribute('aria-pressed','false');document.querySelector('#start').hidden=true;document.querySelector('#gameover').hidden=true;enemies.forEach(e=>scene.remove(e));enemies=[];wave=1;xp=coins=0;stamina=100;voidEnergy=45;hero=fighter(roster[selected].name,roster[selected].color,roster[selected].weapon);hero.userData.max=hero.userData.health=roster[selected].hp;hero.userData.speed=roster[selected].speed;hero.userData.power=roster[selected].power;scene.add(hero);ui.heroName.textContent=roster[selected].name;ui.heroClass.textContent=roster[selected].role;ui.portrait.textContent=roster[selected].initial;game=true;spawnWave();notify('VOID GATE OPENED')}
function spawnWave(){for(let i=0;i<Math.min(2+wave,6);i++)spawnEnemy(i);ui.wave.textContent=String(wave).padStart(2,'0');notify(`WAVE ${String(wave).padStart(2,'0')}`)}
function nearest(){return enemies.filter(e=>e.userData.alive).sort((a,b)=>hero.position.distanceTo(a.position)-hero.position.distanceTo(b.position))[0]}
function damage(target,amount){if(!target?.userData.alive)return;audio.play(target===hero?75:140,.045,'square',.02);target.userData.health-=amount;target.userData.hit=.2;if(target===hero){notify('VOID STRIKE!');if(target.userData.health<=0)end(false)}else if(target.userData.health<=0){target.userData.alive=false;xp+=24;coins+=7;voidEnergy=Math.min(100,voidEnergy+18);notify(`${target.userData.name} DEFEATED`);setTimeout(()=>{scene.remove(target);enemies=enemies.filter(x=>x!==target);if(!enemies.length&&game){if(wave>=5){setTimeout(()=>end(true),700)}else{wave++;setTimeout(()=>{if(game)spawnWave()},900)}}},450)}}
function attack(kind){if(!game||hero.userData.attackCd>0)return;const heavy=kind==='heavy',ability=kind==='void';if(ability&&voidEnergy<35){notify('VOID ENERGY REQUIRED');return}if(heavy&&stamina<20){notify('STAMINA LOW');return}hero.userData.attackCd=ability?.7:heavy?.55:.32;stamina-=heavy?22:ability?0:8;if(ability){voidEnergy-=35;notify('PHANTOM STRIKE')}audio.play(ability?190:heavy?110:240,ability?.15:.05,ability?'sawtooth':'triangle',ability?.06:.025);hero.userData.blade.rotation.z=ability?2.3:heavy?1.5:.75;setTimeout(()=>hero&& (hero.userData.blade.rotation.z=0),190);enemies.forEach(e=>{const d=hero.position.distanceTo(e.position);if(d<(ability?5:2.3)){damage(e,hero.userData.power*(ability?2.4:heavy?1.7:1));e.position.add(e.position.clone().sub(hero.position).normalize().multiplyScalar(.45))}})}
function dodge(){if(!game||stamina<18)return;stamina-=18;audio.play(380,.07,'sine',.025);const v=new THREE.Vector3();camera.getWorldDirection(v);v.y=0;v.normalize();hero.position.addScaledVector(v,-2.2);notify('VOID DASH')}
function end(win){game=false;document.querySelector('#gameover').hidden=false;document.querySelector('#endTitle').textContent=win?'VICTORIOUS':'FALLEN';document.querySelector('#endText').textContent=win?'The Void Gate falls silent—for now.':'Kael returns to the temple threshold. Master the timing, then enter again.'}
function input(dt){const x=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),z=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);if(!hero||(!x&&!z))return;const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0)).normalize();const move=forward.multiplyScalar(-z).add(right.multiplyScalar(x)).normalize();hero.position.addScaledVector(move,hero.userData.speed*dt);hero.rotation.y=Math.atan2(move.x,move.z)}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' ')dodge();if(e.key.toLowerCase()==='j')attack('light');if(e.key.toLowerCase()==='k')attack('heavy');if(e.key.toLowerCase()==='q')attack('void');if(e.key==='Tab'){e.preventDefault();locked=nearest();notify(locked?`LOCKED: ${locked.userData.name}`:'NO TARGET')}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();b.dataset.action==='dodge'?dodge():attack(b.dataset.action)}));document.querySelector('#launch').onclick=start;document.querySelector('#restart').onclick=start;document.querySelector('#pause').onclick=()=>{if(!hero)return;game=!game;const button=document.querySelector('#pause');button.textContent=game?'Ⅱ':'▶';button.setAttribute('aria-pressed',String(!game));audio.enable();audio.play(game?420:210);notify(game?'RESUMED':'PAUSED')};
const stick=document.querySelector('#stick');let stickId=null;stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(stickId)});stick.addEventListener('pointermove',e=>{if(e.pointerId!==stickId)return;const r=stick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width/2),y=(e.clientY-r.top-r.height/2)/(r.height/2);keys.a=x<-.2;keys.d=x>.2;keys.w=y<-.2;keys.s=y>.2;stick.querySelector('i').style.transform=`translate(${Math.max(-25,Math.min(25,x*30))}px,${Math.max(-25,Math.min(25,y*30))}px)`});['pointerup','pointercancel'].forEach(n=>stick.addEventListener(n,()=>{stickId=null;['a','d','w','s'].forEach(k=>keys[k]=false);stick.querySelector('i').style.transform=''}));
function adaptRenderQuality(dt){frameSamples.push(dt);if(frameSamples.length<90||performance.now()-lastPerformanceCheck<1000)return;const average=frameSamples.reduce((sum,value)=>sum+value,0)/frameSamples.length;frameSamples.length=0;lastPerformanceCheck=performance.now();const next=average>.031?Math.max(.75,renderScale-.15):average<.019?Math.min(Math.min(devicePixelRatio,1.5),renderScale+.1):renderScale;if(next!==renderScale){renderScale=next;renderer.setPixelRatio(renderScale);renderer.setSize(innerWidth,innerHeight,false)}}
function tick(){requestAnimationFrame(tick);const dt=Math.min(clock.getDelta(),.04);adaptRenderQuality(dt);if(game&&hero){input(dt);hero.userData.attackCd=Math.max(0,hero.userData.attackCd-dt);stamina=Math.min(100,stamina+dt*15);voidEnergy=Math.min(100,voidEnergy+dt*2);enemies.forEach(e=>{if(!e.userData.alive)return;const to=hero.position.clone().sub(e.position),d=to.length();e.lookAt(hero.position.x,0,hero.position.z);if(d>1.55)e.position.addScaledVector(to.normalize(),e.userData.speed*dt);else if(e.userData.attackCd<=0){e.userData.attackCd=1.1+Math.random()*.7;damage(hero,e.userData.power)}e.userData.attackCd=Math.max(0,e.userData.attackCd-dt);e.userData.body.material.emissive?.setHex(e.userData.hit>0?0xff3040:0x000000);e.userData.hit-=dt});const target=locked?.userData.alive?locked:nearest();ui.target.textContent=target?.userData.name||'—';ui.enemy.style.width=`${target?Math.max(0,target.userData.health/target.userData.max*100):0}%`;ui.health.style.width=`${Math.max(0,hero.userData.health/hero.userData.max*100)}%`;ui.stamina.style.width=`${stamina}%`;ui.void.style.width=`${voidEnergy}%`;ui.xp.textContent=String(xp).padStart(3,'0');ui.coins.textContent=String(coins).padStart(3,'0');const desired=hero.position.clone().add(new THREE.Vector3(0,7,10));camera.position.lerp(desired,.07);camera.lookAt(hero.position.x,1,hero.position.z);gate.rotation.z+=dt*.08;ring.material.emissiveIntensity=2+Math.sin(performance.now()*.004)}renderer.render(scene,camera)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(renderScale);renderer.setSize(innerWidth,innerHeight,false)}addEventListener('resize',resize);resize();tick();
