const C=(title,items)=>`<div class="cards">${items.map(([h,p])=>`<article class="card"><b>${h}</b><p>${p}</p></article>`).join('')}</div>`;
const L=items=>`<ul class="list">${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const D=(items,cls='')=>`<div class="diagram ${cls}">${items.map((x,i)=>`<div class="node ${i===0?'active':''}">${x}</div>`).join('')}</div>`;
const slides=[
 {e:'ORIGINAL CINEMATIC ACTION RPG',t:'VOID<span>BORN</span>',p:'A premium stylized-realistic 3D action RPG built for mobile. Master the power within—or let it master you.',type:'title'},
 {e:'02 — GAME VISION',t:'AWAKEN THE <span>VOID</span>',p:'A mysterious world where ancient powers have awakened. An amnesiac warrior discovers a supernatural force inside him—and a destiny larger than survival.',x:C('',[['3D CINEMATIC COMBAT','Expressive martial arts, weapons, and controlled supernatural force.'],['RPG PROGRESSION','Grow Kael through equipment, skills, builds, and mastery.'],['A WORLD TO UNCOVER','Explore haunted regions, meet Voidbound rivals, and expose a buried truth.']])},
 {e:'03 — CORE PLAYER EXPERIENCE',t:'FROM MYSTERY TO <span>MASTERY</span>',p:'The emotional spine turns uncertainty into agency—then tests what the player does with that power.',x:`<div class="journey">${['MYSTERY','DISCOVERY','COMBAT','POWER','CHOICE','CONSEQUENCE','MASTERY'].map((x,i)=>`<div>${x}</div>${i<6?'<i></i>':''}`).join('')}</div><p class="emotion">POWERFUL &nbsp;•&nbsp; CURIOUS &nbsp;•&nbsp; CHALLENGED &nbsp;•&nbsp; REWARDED &nbsp;•&nbsp; IMMERSED &nbsp;•&nbsp; CONNECTED</p>`},
 {e:'04 — GAME CORE LOOP',t:'THE MOMENTUM <span>LOOP</span>',p:'Every encounter feeds an immediately useful choice, while elite gates and story revelations pull the player into the next region.',x:`<div class="loop">${['EXPLORE','ENCOUNTER ENEMIES','FIGHT','EARN XP / LOOT','UPGRADE CHARACTER','UPGRADE WEAPON','UNLOCK ABILITY','DEFEAT ELITE','BOSS BATTLE','STORY REVEAL','NEW REGION'].map(x=>`<div>${x}</div>`).join('')}</div><p class="lead">Short-term mastery produces rewards; long-term progression opens new combat expression, secrets, and high-stakes bosses.</p>`},
 {e:'05 — STORY PREMISE',t:'THE GATE <span>REMEMBERS</span>',p:'Kael wakes beneath an ancient temple with no memory, black-and-cyan energy coursing through his body. When the Void Gate activates, dormant gates open across the world—and warriors known as the Voidbound emerge.',x:`<p class="quote">“WHO AM I? WHY WAS I CHOSEN? WHAT HAPPENED TO MY PAST? <em>SHOULD THE VOID BE DESTROYED?</em>”</p>`},
 {e:'06 — STORY THEMES',t:'POWER HAS A <span>PRICE</span>',p:'Answers are earned, never dumped. Each region reveals a fragment that changes the meaning of what came before.',x:C('',[['IDENTITY','Who remains when your past is missing?'],['POWER & CORRUPTION','Can a force be controlled without changing its bearer?'],['CHOICE & FREE WILL','Control versus chaos; revenge versus sacrifice; humanity versus power.']])},
 {e:'07 — MAIN CHARACTER',t:'KAEL, THE <span>VOIDBORN</span>',p:'Quiet. Determined. Observant. Emotionally controlled. Kael begins as an unknown survivor and gradually earns the confidence to define his own purpose.',x:`<div class="split"><div>${L(['Dark layered combat outfit with lightweight armor and cloth movement.','Arm guards, boots, and a distinctive waist / shoulder accessory create a strong silhouette.','Original, strong but human face design—never derivative of existing game characters.'])}</div><div class="character"><div class="orb"></div></div></div>`},
 {e:'08 — HERO COLOR DESIGN',t:'A SIGNAL IN THE <span>DARK</span>',p:'Kael’s palette makes control, escalation, and achievement readable at a glance.',x:`<div class="swatches">${[['OBSIDIAN BLACK','#0B0D10'],['CHARCOAL','#20242B'],['ELECTRIC CYAN','#00E5FF'],['DEEP VIOLET','#7C3AED'],['SILVER','#D7DCE2'],['WARM GOLD','#FFC857']].map(([n,c])=>`<div class="swatch" style="background:linear-gradient(135deg,${c},#0b0d10)"><b>${n}</b><small>${c}</small></div>`).join('')}</div><p class="lead">Black / charcoal: mystery & combat identity. Cyan: controlled Void. Violet: advanced power. Gold: legendary achievement.</p>`},
 {e:'09 — GLOBAL COLOR SYSTEM',t:'COLOR IS <span>GAMEPLAY</span>',p:'A tightly governed palette stays consistent across characters, VFX, UI, weapons, and environments.',x:D(['HERO<br>CYAN + VIOLET','NORMAL<br>METAL + MUTED RED','ELITE<br>CRIMSON + BLACK','BOSS<br>CRIMSON + VIOLET','VOID<br>CYAN + VIOLET','LEGENDARY<br>GOLD + BLACK','HEALTH<br>CRIMSON','STAMINA<br>AMBER / GOLD','SPECIAL<br>ELECTRIC CYAN'])},
 {e:'10 — 3D ART DIRECTION',t:'PREMIUM. <span>NOT NOISY.</span>',p:'Stylized-realistic 3D for a cinematic mobile game: detailed models and believable materials, supported by stylized proportions and strong silhouettes.',x:`<div class="split"><div><h3>CREATE</h3>${L(['High-quality weapons and atmospheric environments.','Cinematic lighting and controlled VFX.','Readable silhouettes at mobile scale.'])}</div><div><h3>AVOID</h3>${L(['Excessive cartoon styling.','Generic mobile-game presentation.','Expensive photorealism and visual clutter.'])}</div></div>`},
 {e:'11 — CAMERA SYSTEM',t:'CINEMATIC, ALWAYS <span>READABLE</span>',p:'A behind-the-player third-person camera that protects combat clarity while making power feel dramatic.',x:C('',[['TRACK','Dynamic distance, soft tracking, and environmental transitions.'],['LOCK','Target lock keeps threat priority clear without obscuring the arena.'],['IMPACT','Attack shake, special-attack framing, boss introductions, and victory shots.']])},
 {e:'12 — COMBAT SYSTEM',t:'TIMING OVER <span>BUTTONS</span>',p:'Responsive real-time 3D combat with a clear timing language—not a button-mashing race.',x:`<div class="sequence">${['LIGHT','HEAVY','KICK','JUMP','BLOCK','DODGE','COUNTER','GRAB','THROW','FINISHER','VOID','ULTIMATE'].map(x=>`<div>${x}</div>`).join('')}</div><p class="lead">Players chain martial arts, weapons, aerial attacks, and finishers; defense creates decisive openings.</p>`},
 {e:'13 — MOBILE CONTROLS',t:'CONTROL WITHOUT <span>COMPROMISE</span>',p:'A premium touch layout that works across screen sizes and respects player comfort.',x:`<div class="split"><div class="character"><div class="orb"></div></div><div>${L(['LEFT: virtual joystick.','RIGHT: Light, Heavy, Dodge, Block, and Special.','Optional target lock.','Reposition, resize, set transparency, and adjust sensitivity.'])}</div></div>`},
 {e:'14 — COMBAT MECHANICS',t:'READ THE <span>FIGHT</span>',p:'Interlocking resources and reactions make every defense and offense meaningful.',x:C('',[['HEALTH / STAMINA','Health is survival; stamina limits reckless offense and evasions.'],['VOID / COMBO','Void Energy fuels abilities. Combo Meter rewards sustained precision.'],['STAGGER / POISE','Break poise to stagger; preserve your own to keep control.'],['PERFECT DODGE','Evade just before impact: brief slow motion + counter opportunity.'],['PERFECT BLOCK','Block at the exact impact point to create enemy stagger.'],['COUNTER WINDOW','A short, readable opportunity to reverse momentum.']])},
 {e:'15 — COMBO SYSTEM',t:'A LANGUAGE OF <span>IMPACT</span>',p:'Combos are readable and weapon-specific, with clean routes from ground control to supernatural payoff.',x:`<div class="sequence">${['LIGHT','LIGHT','HEAVY','KICK','DASH','SPECIAL'].map(x=>`<div>${x}</div>`).join('')}</div><div class="sequence">${['LIGHT','LIGHT','HEAVY','LAUNCH','AIR ATTACK','DASH','VOID STRIKE'].map(x=>`<div>${x}</div>`).join('')}</div>`},
 {e:'16 — WEAPON SYSTEM',t:'SEVEN WAYS TO <span>FIGHT</span>',p:'Every class has damage, speed, range, combo pattern, special attack, and passive ability.',x:D(['KATANA<br>FAST / PRECISE','DUAL BLADES<br>RAPID','SPEAR<br>LONG RANGE','HEAVY AXE<br>DEVASTATING','STAFF<br>CONTROL','CHAIN BLADE<br>UNIQUE RANGE','VOID GAUNTLETS<br>CLOSE-RANGE POWER'])},
 {e:'17 — WEAPON VISUAL DESIGN',t:'FORGED FOR A <span>LEGEND</span>',p:'Premium original 3D weapons combine forged metal, dark steel, leather, energy crystals, and ancient symbols.',x:C('',[['BASE MATERIALS','Dark steel, worn leather, forged edges, and believable construction.'],['RARITY LANGUAGE','Cyan energy, violet glow, gold engraving, and animated Void effects.'],['DESIGN RULE','Distinct silhouettes and lore—never visually copied from existing IP.']])},
 {e:'18 — VOID POWER SYSTEM',t:'THE GAME’S <span>SIGNATURE</span>',p:'Void energy builds during combat. Every ability carries energy cost, cooldown, animation, VFX, sound, and counterplay.',x:D(['VOID DASH<br>SHORT TELEPORT','PHANTOM STRIKE<br>RAPID ASSAULT','SHADOW CLONE<br>TEMPORARY PROJECTION','GRAVITY BREAK<br>PULL & CONTROL','VOID WAVE<br>LONG-RANGE','VOID FORM<br>ULTIMATE'])},
 {e:'19 — VOID FORM',t:'BECOME THE <span>STORM</span>',p:'A limited ultimate transformation: cyan/violet eyes, energy markings, floating particles, transformed dark armor, trails, and more forceful attack animation.',x:`<p class="quote">EXTREMELY POWERFUL.<br><em>NEVER PERMANENT.</em></p><p class="lead">Its short duration makes activation a cinematic commitment instead of a default state.</p>`},
 {e:'20 — ENEMY DESIGN',t:'EVERY FOE HAS A <span>QUESTION</span>',p:'Distinct enemy classes force a strategic response rather than interchangeable damage races.',x:D(['RUSHER<br>FAST MELEE','GUARDIAN<br>DEFENSIVE','ASSASSIN<br>EVASIVE','RANGED<br>PROJECTILES','BERSERKER<br>LOW-HP FURY','VOID MAGE<br>SUPERNATURAL','ELITE<br>UNIQUE MODIFIERS'])},
 {e:'21 — ENEMY AI',t:'INTENT, NOT <span>SPAM</span>',p:'State-driven AI reacts to player distance, health, patterns, blocks, and dodges—creating openings and believable pressure.',x:D(['IDLE','PATROL','DETECT','APPROACH','ATTACK','BLOCK','DODGE','RETREAT','STAGGER','RECOVER','SPECIAL','DEFEATED'])},
 {e:'22 — BOSS SYSTEM',t:'BOSSES ARE <span>REVELATIONS</span>',p:'Each cinematic boss has readable patterns and a narrative function—not merely a larger health bar.',x:`<div class="timeline">${['INTRODUCTION','PHASE 1','PHASE 2','TRANSFORMATION','FINAL ATTACK','DEFEAT','STORY REVEAL'].map(x=>`<div>${x}</div>`).join('')}</div>`},
 {e:'23 — MAJOR BOSSES',t:'THE <span>VOIDBOUND</span> RISE',p:'Six original rivals express different philosophies of power and combat.',x:C('',[['THE IRON MONK','Heavy staff · defensive martial arts.'],['THE BLOOD HUNTER','Twin blades · relentless assassin.'],['THE FROZEN WARDEN','Massive spear · control and area attacks.'],['THE VOID GENERAL','Ancient greatsword · aggressive hybrid.'],['THE MASKED KING','Royal blade · precision and counters.'],['THE ABYSSAL WARDEN','Final boss · multi-phase Void manipulation.']])},
 {e:'24 — WORLD DESIGN',t:'A WORLD OF <span>WOUNDS</span>',p:'Six regions each have a gameplay identity, emotional temperature, and controlled palette.',x:C('',[['FORGOTTEN TEMPLE','Black · stone grey · cyan'],['ASHEN VILLAGE','Charcoal · orange · muted red'],['CRIMSON FOREST','Dark green · crimson · violet'],['FROZEN FORTRESS','Blue · white · silver'],['SUNKEN CITY','Deep blue · cyan · black'],['VOID CITADEL','Obsidian · violet · crimson · cyan']])},
 {e:'25 — ENVIRONMENT DESIGN',t:'DEPTH YOU CAN <span>FEEL</span>',p:'Every scene composes foreground, gameplay area, background, and atmosphere for depth without sacrificing readability.',x:`<div class="art-bullets">${['Fog & volumetric lighting','Particles & dynamic shadows','Rain, fire, and dust','Floating debris','Environmental animation','Controlled local color'].map(x=>`<div>${x}</div>`).join('')}</div>`},
 {e:'26 — LEVEL STRUCTURE',t:'PATHS THROUGH THE <span>UNKNOWN</span>',p:'Each region supports a clear campaign route, then invites confident players to take meaningful detours.',x:D(['STORY MISSION','COMBAT MISSION','ELITE MISSION','CHALLENGE MISSION','EXPLORATION AREA','BOSS MISSION'])},
 {e:'27 — CHARACTER PROGRESSION',t:'GROW WITH <span>INTENTION</span>',p:'Progression reinforces mastery with stat growth, ability options, and equipment improvements.',x:`<div class="sequence">${['XP','LEVEL UP','SKILL POINTS','NEW ABILITIES','BETTER EQUIPMENT','NEW REGIONS'].map(x=>`<div>${x}</div>`).join('')}</div><p class="lead">Core stats: Health · Attack · Defense · Stamina · Speed · Critical Chance · Void Power.</p>`},
 {e:'28 — SKILL TREE',t:'BUILD YOUR <span>VOIDBORN</span>',p:'Five branches let players develop a personal combat identity while preserving the game’s clarity.',x:D(['COMBAT<br>COMBOS & DAMAGE','DEFENSE<br>BLOCK / DODGE / COUNTER','WEAPON<br>CLASS ABILITIES','MOBILITY<br>DASH & AERIAL','VOID<br>SUPERNATURAL POWER'])},
 {e:'29 — EQUIPMENT SYSTEM',t:'EQUIP THE <span>UNKNOWN</span>',p:'Six slots with coherent, legible stats and rarity—not inventory clutter.',x:`<div class="split"><div>${L(['Slots: Weapon, Head, Chest, Arms, Legs, Accessory.','Stats: Attack, Defense, Health, Stamina, Void Energy, Critical Chance.'])}</div><div>${D(['COMMON','UNCOMMON','RARE','EPIC','MYTHIC','VOID'])}</div></div>`},
 {e:'30 — GAME MODES',t:'MORE WAYS TO <span>MASTER</span>',p:'Build repeatable engagement around combat first; PvP remains a future option, never the foundation.',x:C('',[['STORY MODE','The main cinematic campaign.'],['SURVIVAL / BOSS RUSH','Endless waves or consecutive boss mastery.'],['CHALLENGE / TRAINING','Special rules and low-pressure practice.'],['DAILY TRIAL','Rotating high-value challenge.']])},
 {e:'31 — UI DESIGN',t:'QUIET UI. <span>LOUD ACTION.</span>',p:'Modern dark translucent panels, cyan/violet accents, and a mobile-first information hierarchy.',x:`<div class="split"><div><h3>MAIN MENU</h3>${L(['Continue · Story · Character','Weapons · Skills · Challenges · Settings'])}</div><div><h3>BATTLE HUD</h3>${L(['Player & enemy health','Stamina · Void Energy · Combo Counter','Ability cooldowns'])}</div></div>`},
 {e:'32 — UI COLOR SYSTEM',t:'A SINGLE VISUAL <span>LANGUAGE</span>',p:'Obsidian #0B0D10 · Charcoal #20242B · Cyan #00E5FF · Violet #7C3AED · Crimson #FF3040 · Gold #FFC857 · Silver #D7DCE2.',x:`<p class="quote">CLEAN. LEGIBLE.<br><em>MADE FOR MOBILE.</em></p>`},
 {e:'33 — VFX DESIGN',t:'EFFECTS WITH <span>PURPOSE</span>',p:'VFX clarify timing, scale, and danger. They never hide a counter window or opponent silhouette.',x:C('',[['COMBAT','Sparks, dust, impact flashes, trails, hit particles, ground impact.'],['VOID','Cyan energy, violet smoke, distortion, rings, trails, gravity.'],['BOSS','Large-scale reactions, controlled slow motion, and shake.']])},
 {e:'34 — ANIMATION SYSTEM',t:'RESPONSIVENESS IS <span>THE FANTASY</span>',p:'Every animation must preserve player control, readable recovery, and combat weight.',x:D(['IDLE / WALK / RUN','JUMP / FALL','LIGHT / HEAVY / KICK','BLOCK / DODGE / ROLL','COUNTER / HIT / STAGGER','WEAPON / SPECIAL / ULTIMATE','VICTORY / DEFEAT'])},
 {e:'35 — AUDIO DESIGN',t:'HEAR THE <span>IMPACT</span>',p:'Original or properly licensed sound grounds every blow and makes the world feel ancient, dangerous, and alive.',x:C('',[['COMBAT','Punch impact, weapon clash, heavy impact, block, dodge, counter, boss attacks.'],['WORLD','Wind, rain, fire, footsteps, temple, forest, and water ambience.'],['MUSIC','Dark cinematic score: traditional-inspired instruments + modern orchestral intensity.']])},
 {e:'36 — PROGRESSION & ECONOMY',t:'REWARD SKILL. <span>NOT SPENDING.</span>',p:'Coins support normal play; Void Shards power rare progression; materials improve equipment.',x:`<div class="split"><div><h3>MONETIZE FAIRLY</h3>${L(['Cosmetic and weapon skins','Optional bundles and battle pass','Rewarded ads and premium story expansions'])}</div><div><p class="quote"><em>NO PAY TO WIN.</em></p><p class="lead">Core combat stays skill-based.</p></div></div>`},
 {e:'37 — DAILY / WEEKLY CONTENT',t:'REASONS TO <span>RETURN</span>',p:'A cadence of respectful repeatable content rewards commitment without replacing the campaign.',x:C('',[['DAILY','Challenge · reward · training mission.'],['WEEKLY','Boss · special challenge · limited cosmetic.'],['LONG-TERM','Achievements · weapon collection · boss and skill mastery.']])},
 {e:'38 — TECHNICAL ARCHITECTURE',t:'BUILT IN <span>UNITY</span>',p:'C# systems are modular, testable, and connected through a clear gameplay core.',x:D(['PLAYER CONTROLLER','COMBAT CONTROLLER','WEAPON SYSTEM','ENEMY / BOSS AI','ANIMATION / CAMERA','ABILITY SYSTEM','INVENTORY / PROGRESSION','SAVE SYSTEM','UI / AUDIO / VFX','MISSION MANAGER'])},
 {e:'39 — 3D ASSET PIPELINE',t:'FROM CONCEPT TO <span>COMBAT</span>',p:'Every asset is designed with mobile quality and budget discipline in mind.',x:`<div class="sequence">${['CONCEPT','MODEL','RETOPOLOGY','UV','TEXTURE','RIG','ANIMATE','UNITY','MATERIALS','VFX','OPTIMIZE','TEST'].map(x=>`<div>${x}</div>`).join('')}</div>`},
 {e:'40 — MOBILE OPTIMIZATION',t:'BEAUTY AT <span>60 FPS</span>',p:'Target stable 30–60 FPS depending on device, with transparent graphics presets from Low to Ultra.',x:C('',[['RENDERING','LODs, texture compression, baked lighting, occlusion culling, fewer draw calls.'],['GAMEPLAY','Object pooling, efficient AI, particle limits, adaptive resolution.'],['PLAYER CHOICE','LOW · MEDIUM · HIGH · ULTRA graphics presets.']])},
 {e:'41 — MVP',t:'POLISH ONE GREAT <span>FIGHT</span>',p:'The first playable prototype is intentionally small: 5–10 minutes that prove the game’s feel.',x:C('',[['ONE HERO / ARENA','One 3D character, one weapon, one arena, three enemy types, mini-boss.'],['CORE FIGHT','Light, heavy, kick, block, dodge, combo, health, stamina, Void Strike.'],['PROVE THE LOOP','Basic AI, XP, upgrade, mobile controls, victory and defeat screens.']])},
 {e:'42 — DEVELOPMENT ROADMAP',t:'FROM MOTION TO <span>RELEASE</span>',p:'A disciplined production sequence protects the combat core before expanding content.',x:`<div class="timeline">${['MOVEMENT','COMBAT','AI','WEAPONS','BOSS','ENVIRONMENT','PROGRESSION','STORY','POLISH','OPTIMIZE','TEST','ANDROID RC'].map((x,i)=>`<div>P${i+1}<br>${x}</div>`).join('')}</div>`},
 {e:'43 — DEVELOPMENT PRIORITY',t:'COMBAT BEFORE <span>CONTENT</span>',p:'“Great combat comes before massive content.” The priority stack protects that promise.',x:D(['1. COMBAT FEEL','2. CONTROLS','3. RESPONSIVENESS','4. ENEMY AI','5. PERFORMANCE','6. BOSS DESIGN','7. PROGRESSION','8. LEVEL DESIGN','9. STORY','10. VISUAL POLISH','11. MONETIZATION','12. EXTRA FEATURES'])},
 {e:'44 — RISKS',t:'MAKE RISK <span>VISIBLE</span>',p:'Scope discipline and early technical validation prevent a cinematic ambition from becoming production debt.',x:`<div class="risk">${[['Large scope','Vertical-slice first; defer regions and modes.'],['3D / animation workload','Modular kits, reuse rigs, prioritize combat set.'],['Mobile performance','Budgets, profiling, scalable presets from day one.'],['AI complexity','State machines first; add behavior only when it improves combat.'],['Content & storage','Reuse systems, compressed assets, lean launch plan.'],['Monetization / IP risk','Cosmetics only; original design reviews and references policy.']].map(x=>`<div>${x[0]}</div><div>${x[1]}</div>`).join('')}</div>`},
 {e:'45 — ORIGINALITY / IP PROTECTION',t:'OWN THE <span>LEGEND</span>',p:'VOIDBORN is an original world, story, visual language, character roster, combat identity, and asset library.',x:`<p class="quote">INSPIRED BY THE <em>STANDARD</em>.<br>NEVER BY SOMEONE ELSE’S IDENTITY.</p><p class="lead">Use original names, silhouettes, lore, animation, sound, UI, VFX, and weapon design. Document references, license every external asset, and review every feature for avoidable similarity.</p>`}
];
const deck=document.getElementById('deck');
deck.innerHTML=slides.map((s,i)=>`<section class="slide ${s.type==='title'?'title-slide':''}" id="slide-${i+1}"><div class="eyebrow">${s.e}</div><h1>${s.t}</h1>${s.p?`<p class="lead">${s.p}</p>`:''}${s.x||''}${s.type==='title'?'<div class="rule"></div><div class="void-ring"></div>':''}</section>`).join('');
let current=0; const progress=document.getElementById('progress'), counter=document.getElementById('counter');
function show(n){current=(n+slides.length)%slides.length;document.querySelectorAll('.slide').forEach((s,i)=>s.classList.toggle('active',i===current));location.hash=`/${current+1}`;counter.textContent=`${String(current+1).padStart(2,'0')} / ${slides.length}`;progress.style.width=`${((current+1)/slides.length)*100}%`;}
function fromHash(){let n=Number(location.hash.slice(2))-1;if(Number.isInteger(n)&&n>=0&&n<slides.length)show(n);else show(0)}
addEventListener('keydown',e=>{if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();show(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}if(e.key==='Escape')panel.hidden=true});addEventListener('hashchange',fromHash);
const panel=document.getElementById('overviewPanel'), thumbs=document.getElementById('thumbs');thumbs.innerHTML=slides.map((s,i)=>`<button class="thumb" data-slide="${i}"><b>${s.e}</b><span>${s.t.replace(/<[^>]+>/g,' ')}</span></button>`).join('');
document.getElementById('overview').onclick=()=>panel.hidden=false;document.getElementById('closeOverview').onclick=()=>panel.hidden=true;thumbs.onclick=e=>{let b=e.target.closest('[data-slide]');if(b){show(+b.dataset.slide);panel.hidden=true}};fromHash();
